### ISSUE TITLE
Add support for encrypted ssh keys

### ISSUE THREAD

**Issue by ajoliveau** [burgerbuds/swiff#11]
If the ssh key is protected by a passphrase, it fails (gracefully) with this message :
> 💁‍  Error: Encrypted private key detected, but no passphrase given

It would be great if support for encrypted key would be added (either by just asking for the passphrase, or in my case the passphrase is stored in the OSX keychain so I usually just do a `ssh-add -K` at the beginning of my session and don't have to worry about it after

**Comment by ben-rogerson** [comment]
That's a great idea 👏 
I'll push support for passphrase protected keys in one of the next releases.
I'll let you know when it's released
