### ISSUE TITLE
Enable multiple environments per project

### ISSUE THREAD

**Issue by ajoliveau** [burgerbuds/swiff#12]
I would love a feature where I could have multiple environments setup in the config (for example a dev environment, a staging environment and even the prod environment).
Each should have its own push and pull folders.

**Comment by ben-rogerson** [comment]
I agree - configuring Swiff for additional environments would be genuinely useful. 
I'll look into adding this, thanks for the idea

**Comment by ben-rogerson** [comment]
For the time being Swiff is focussed on "Local <> Staging server" functionality so closing this for now.

**Comment by chasegiunta** [comment]
@ben-rogerson Wondering, if in the interim, a cli param could be added to designate a config file?

Such as
`swiff --config staging.swiff.js`
`swiff --config production.swiff.js`
(config file could be named whatever, as long as it's parsable by swiff)

We currently have multiple config files & renaming.

**Comment by ben-rogerson** [comment]
@chasegiunta I'm thinking multiple configs would be a great feature for the release after next.
Here's some thoughts:
- I'd like to be able to specify the config via flags or the interface
- Config file naming should be enforced: `swiff.[production/staging/etc].js`
- The flag could be: `swiff --config production` or `swiff production`
- We'd need to display the current loaded config in the interface
- An options screen to switch configs would be needed
- A reference to the last used config could be stored

Let me know what you think

**Comment by chasegiunta** [comment]
@ben-rogerson The additional config files were simply a workaround. I don't think, long-term, it would make sense for a config file per environment. My guess would be that placing them in one file massively complicates things with how everything is currently being done, though.

Understandably, if it's too much work right now for a feature _you personally_ may not even use, what you've suggested sounds great.

**Comment by ben-rogerson** [comment]
Yeah you're right, it'll be more complex to deal with the issues around combining the configs.
Going with separate config files means the 'multiple configs' feature could be optional.

For the time being you could try automating the config swap.
Maybe you could use a package.json script like this?
```js
"scripts": {
    "swapconfig": "mv swiff.config.js tmp && mv swiff.secondary.js swiff.config.js && mv tmp swiff.secondary.js"
  },
```
