### ISSUE TITLE
Change default colours?

### ISSUE THREAD

**Issue by shornuk** [burgerbuds/swiff#19]
Hi, 
Using nicely with a few projects. One thing, the teal font colour on the task interface is difficult to read on a white background. Is there a way to change?

<img width="575" alt="Screenshot 2019-05-16 at 11 35 15" src="https://user-images.githubusercontent.com/2061819/57847582-b1b66600-77ce-11e9-947b-2fe0f260fca6.png">

**Comment by ben-rogerson** [comment]
Hey there Sean 👋

Oh my, that _is_ hard to read.
I've looked into some possible fixes but it's proving difficult as there's currently no global Swiff config to set these kinds of things. 
I could adjust the teal for everyone but I feel it may have already become part of the Swiff "branding".

For now, perhaps you could adjust the palette on your side:
/usr/local/lib/node_modules/swiff/dist/palette.js
Line 15: const hexHighlight = '#6EFFBF';

**Comment by shornuk** [comment]
Thanks for that. Changing it locally works for now. 👍

**Comment by ben-rogerson** [comment]
No worries, there's a couple of features in the pipeline that also require a global config so there's a good chance this feature will be added with them
