### ISSUE TITLE
Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by shornuk** [burgerbuds/swiff#53]
Trying to use on a newly configured server. Keep getting the following error when trying to pull the database.

`Error: All configured authentication methods failed`

My ssh key is installed on the server and everything is set up the same way as other sites. 

Only difference is that this is the first site that's on Craft 4 - could that be an issue?

**Comment by samstevens** [comment]
Hey @shornuk,

Are you using an ed25519 key?

In your project .env file, try specifying a custom key:

SWIFF_CUSTOM_KEY="/Users/username/.ssh/id_ed25519"

Hope this helps.

**Comment by shornuk** [comment]
Frustratingly I seem to have hit this error again. 

> Are you using an ed25519 key?

Not using an ed25519 key, no. 

From what I can tell, everything is set up the same as my sites that currently use swiff and work fine. I can ssh in to my site fine. I can use swiff to pull assets fine, but when trying to pull the database, I keep getting the above error.

**Comment by shornuk** [comment]
OK, I have this working. For future reference, I;ve just created a new SSH key as per the docs and that's now working. 👍
